# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Sample_n <- function(n_iter, L, R, edge, distance, X, Y, transition_matrix, pi_distro, prior_r2_a, prior_r2_b, prior_r3_a, prior_r3_b, prior_zr_1, prior_gc_a, prior_gc_b, prior_lc_a, prior_lc_b, prior_ac_a, prior_ac_b, prior_root_u, prior_root_sd, prior_lv_u, prior_lv_sd, prior_lb2_u, prior_lb2_sd, prior_lb3_u, prior_lb3_sd, do_Y, uniform_prior_lv, inner_iter, verbose) {
    .Call(`_pac3_Sample_n`, n_iter, L, R, edge, distance, X, Y, transition_matrix, pi_distro, prior_r2_a, prior_r2_b, prior_r3_a, prior_r3_b, prior_zr_1, prior_gc_a, prior_gc_b, prior_lc_a, prior_lc_b, prior_ac_a, prior_ac_b, prior_root_u, prior_root_sd, prior_lv_u, prior_lv_sd, prior_lb2_u, prior_lb2_sd, prior_lb3_u, prior_lb3_sd, do_Y, uniform_prior_lv, inner_iter, verbose)
}

